import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import ModeToggle from "@/components/mode-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <br />
            <br />
             <div className="container mx-auto">{children}</div>
            <div className="fixed bottom-4 right-4">
                        <ModeToggle />
                    </div>
          </ThemeProvider>
        </body>
    </html>
  );
}
